### PR TITLE
Super fun happy everything.

### LINKED ISSUE #17: Split into sub-modules
@bondjimbond 
I did this, but I don't use scholar nor badges so I need some help with testing.

My branch is here https://github.com/whikloj/islandora_badges/tree/7.x-merged

I'll keep working and then submit a PR to your repo.

### LINKED ISSUE #19: Configure which Content-Models to display badges on.
Currently altmetrics only displays badges for ir:citationModels.

We could allow people to select which Content-models to display badges on.

### PR DESCRIPTION
**Pull request by whikloj**
This PR subsumes #18 

Resolves #17, resolves #19 

# What does this Pull Request do?

Splits the Altmetrics, Scopus and Web of Science functionality into separate sub-modules of the islandora_badges module.

Allows the configuration of which content-models the badges should appear (currently only implemented on islandora_altmetrics block).

Allows viewing a sample altmetrics badge in configuration to see what it will look like.

# What's new?

* Separate modules for each badge, with their own configuration.
* Shared DOI extraction function and (possibly) the content-model filtering.
* Removed islandora_scholar dependency.
* Removed defaults values and switched to empty strings.

# How should this be tested?

1. Enable the Islandora Badges, Islandora Altmetrics, Islandora Scopus & Islandora WOS modules.
1. Add the 3 blocks to your display.
1. Goto Admin > Islandora > Islandora Utility Modules > Islandora Badges Configuration
1. Select one or more content-model to display badges on. 
1. Save config.
1. Add your Scopus API Key on its config page. Save config.
1. Add your Web Of Science username/password on its config page. Save config.
1. Configure your Altmetrics badge on its config page. Save config.
1. Browse to your objects and see that the badge shows up on the correct content-model and displaying correctly.

**TODO**: This needs an update hook to convert the islandora_badges_altmetrics_... variables back to islandora_altmetrics_... variables.

Example:
* Does this change require documentation to be updated? yes
* Does this change add any new dependencies? no
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? no
* Could this change impact execution of existing code? possibly.

# Interested parties
@bondjimbond @mjordan

### CODE REVIEW

**Comment by whikloj** [comment]
I was able to get Scopus working for me. I changed the functionality slightly to do a query to find the Scopus ID using the DOI and then generate the citation badge using that Scopus ID. In theory you could then just add calls to check for a DOI, PMID, etc.

**Comment by whikloj** [comment]
Here is my test object with an Altmetrics badge.
http://niobe.lib.umanitoba.ca/islandora/object/uofm%3A1246970

Here is my test object for a Scopus badge.
http://niobe.lib.umanitoba.ca/islandora/object/uofm%3A1248037

Unfortunately I don't have Web Of Science, so you might have to correct any mistakes I made in that module. But I can help if you need.

**Comment by bondjimbond** [comment]
@whikloj Scopus and WoS appear to be working as expected (given the same flaws that exist in the 7.x branch) -- but the Altmetric block, at least on install, does not display.

Tried uninstalling everything related to Badges then reinstalling - same deal. Altmetrics block is available in Blocks, but is not appearing on the page.

Swapping back to 7.x makes Altmetrics block reappear, so something in your code is causing it not to display. or perhaps it has to do with the variable conflicts?

**Comment by whikloj** [comment]
@bondjimbond it could be because I added a bunch of different badge types and store them differently in the admin, I'll add a check for your old default "Default" and replace it with the medium badge.

**Comment by bondjimbond** [comment]
Badge type doesn't seem to make a difference - any that I select still fails to display on an object.

**Comment by whikloj** [comment]
Can you give me the URL to one, and I can look and see what is probably happening. The other option is I can add a bunch of watchdog logging statements and you could see what is happening in your logs?

**Comment by bondjimbond** [comment]
This is all testing on my local vagrant machine, so I can't really send you a URL. Sure, add some logging and I can send you the output.

**Comment by whikloj** [comment]
I just realized something, did you select a Content-model in the admin/islandora/tools/badges/common?? Altmetrics is the only badge that uses that selection, but that might be why you are not seeing your badge?

Go to that configuration screen, choose the Content-models to display the badges on and save the configuration.

**Comment by bondjimbond** [comment]
Ha! Yes, that did the trick. Last time I looked at that page, the only config option was for DOI xpath. Didn't realize you'd added a whole set of options to it!

Thanks for identifying that problem.

I've added a fix for the WoS zero citation issue (#12) as well. Might you be able to make a couple of small tweaks before I merge?

- Rearrange menu tab order -- Badges should be first, then Altmetrics
- On Badges config, bring DOI Xpath to the top
- Badges config - make Citation and Thesis selected by default

**Comment by bondjimbond** [comment]
@whikloj Looking over the code, it looks like your $already_chosen variable is intended to provide a default (https://github.com/whikloj/islandora_badges/blob/issue-19/includes/admin.form.inc#L14) - for some reason it didn't take for me. Did the default work for you?

Re the other bits -- I pushed a commit to move the xpath already. Not sure if there's a way to rearrange the tabs, but that's minor.

Pending your answer to the default value question, we're probably ready for merge.

**Comment by whikloj** [comment]
@bondjimbond should be fixed now.

I'll add that we may want to add an update hook to change anyone's `islandora_altmetrics_badge` from using the `Default` to `2`. But that can come as part of replacing islandora_altmetrics with islandora_badges.

**Comment by bondjimbond** [comment]
Looks good! I'm gonna merge. Thanks again for taking care of the submodule issue.

**Comment by mjordan** [comment]
W0000t! Nice work everyone, special shout out to @whikloj !

**Comment by whikloj** [comment]
Thanks all, glad I could help. I'll mention that you all should go through the docs. The main one has nothing about the new content-model selector and the sub-modules might be missing information too.

**Comment by bondjimbond** [comment]
@whikloj Yep, I'll be looking into the readme files today. Some screenshots need replacing too.

**Pull request merged**
