### PR TITLE
7.x merged

### LINKED ISSUE #17: Split into sub-modules
@bondjimbond 
I did this, but I don't use scholar nor badges so I need some help with testing.

My branch is here https://github.com/whikloj/islandora_badges/tree/7.x-merged

I'll keep working and then submit a PR to your repo.

### PR DESCRIPTION
**Pull request by whikloj**
Resolves #17 

# What does this Pull Request do?

Splits the Altmetrics, Scopus and Web of Science functionality into separate modules.

# What's new?

These modules are fairly simple and share very little except the DOI code. This makes it easier to add additional badges with a new module also depending on islandora_badges.

The islandora_badges module just holds the DOI Xpath configuration and a utility function to extract the DOI from an objects MODS record.

It was suggested by @DiegoPino that you could also allow for retrieving the DOI from Solr. So if someone has indexed it, you wouldn't have to parse the MODS each time.

# How should this be tested?

Make sure it still works as expected with objects.

Example:
* Does this change require documentation to be updated? Yes
* Does this change add any new dependencies? No
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? No
* Could this change impact execution of existing code? No

# Interested parties
@mjordan @bondjimbond

### CODE REVIEW

**Comment by DiegoPino** [comment]
@whikloj amazing and so fast++

**Comment by mjordan** [comment]
Yes, @whikloj you are a machine.

**Comment by whikloj** [comment]
I didn't have to code anything, @mjordan and @bondjimbond did all that. Also, I haven't really tested this. I still need to make some objects with DOIs to ensure it all works the same. 😄

**Comment by bondjimbond** [comment]
@whikloj  Fork throws up a lot of errors now.. Not really sure why, since the code hasn't changed that much.

This is what appears on an object WITH DOI (doi:10.1037/0278-6133.23.2.207) and expects a badge for each of Altmetric, WOS, and Scopus:

- Scopus badge doesn't appear at all (should be 638)
- WOS badge shows zero citations (originally 527)
- Altmetric badge is fine

Notices as below:
Notice: Undefined variable: object in islandora_scopus_block_view() (line 46 of /var/www/drupal/sites/all/modules/islandora_badges/modules/islandora_scopus/islandora_scopus.module).
Notice: Trying to get property of non-object in islandora_wos_block_view() (line 109 of /var/www/drupal/sites/all/modules/islandora_badges/modules/islandora_wos/islandora_wos.module).
Notice: Trying to get property of non-object in islandora_wos_block_view() (line 109 of /var/www/drupal/sites/all/modules/islandora_badges/modules/islandora_wos/islandora_wos.module).
Warning: Invalid argument supplied for foreach() in islandora_wos_block_view() (line 109 of /var/www/drupal/sites/all/modules/islandora_badges/modules/islandora_wos/islandora_wos.module).
Notice: Array to string conversion in islandora_wos_block_view() (line 131 of /var/www/drupal/sites/all/modules/islandora_badges/modules/islandora_wos/islandora_wos.module).

**Comment by whikloj** [comment]
Yeah sorry, I'm just setting up some test objects now. I'll run through and see what havoc I have caused.

**Comment by bondjimbond** [comment]
@whikloj Also, objects with no DOI are displaying an undefined variable error for Scopus:

Notice: Undefined variable: object in islandora_scopus_block_view() (line 46 of /var/www/drupal/sites/all/modules/islandora_badges/modules/islandora_scopus/islandora_scopus.module).

**Comment by whikloj** [comment]
@bondjimbond I'm a moron, hold off till Monday. I'm seeing where my speed has resulted in poor coding.

**Comment by whikloj** [comment]
@bondjimbond alright it was not as bad as I thought. I can see altmetrics now, I have to get a WOS and Scopus key to test with them. But you can try again, sorry about that.

**Comment by bondjimbond** [comment]
Cool -- testing now, I get Altmetric (correctly) and WOS (correctly) and Scopus (correctly); no more "undefined variable" errors either.

I'm going to do a little more testing, but it's looking pretty good so far now.

**Comment by bondjimbond** [comment]
@whikloj Still working on it? I did a git pull on your branch and now some PHP syntax error prevents Islandora from loading anything.

**Comment by bondjimbond** [comment]
@whikloj OK, things load properly again without any changes - weird.

Here are some current errors:

On Collection objects:
  Notice: Trying to get property of non-object in islandora_altmetrics_block_view() (line 53 of /var/www/drupal/sites/all/modules/islandora_altmetrics/islandora_altmetrics.module).

  Warning: DOMDocument::loadXML(): Empty string supplied as input in islandora_altmetrics_block_view() (line 53 of /var/www/drupal/sites/all/modules/islandora_altmetrics/islandora_altmetrics.module).


Weird thing -- loading this on a site that has previously had the earlier version of Badges creates TWO Scopus badges - one where you expect it, and one elsewhere. Would be nice if you can get some testing done on a clean site with no baggage, see if same issue.

If you like, I can send you my Scopus API key by email to let you try it out on an object with same DOI.

**Comment by whikloj** [comment]
I got a Scopus key, I'll have a look and see what I might have missed.

**Comment by whikloj** [comment]
I could use a DOI that will return some results from Scopus, I was using your test one from before and I can get Altmetrics results but not Scopus.

Also for that Altmetrics issue... I'm not sure. Line 53 is nothing. Maybe try clearing the Drupal cache in case there is something hanging on and causing issues.

**Comment by whikloj** [comment]
Also, I have now implemented the ability to preview the badge in the altmetrics admin page on my other branch. That branch has all of this code plus quite a bit more.

I think I will push that all here too. I do apologize for this... but I think you'll like it.

Still if you can send me a good Scopus DOI I still need to figure out what is going on there.

Then comes Web Of Science....

**Comment by DiegoPino** [comment]
@whikloj I'm no way an expert on EID or DOI (means I don't know anything!) but this can help since you have a Scopus key 
http://kitchingroup.cheme.cmu.edu/blog/2015/06/07/Getting-a-Scopus-EID-from-a-DOI/  or you can use the example EID (2-s2.0-84881394200). Maybe it's just too late and i don't know what I'm typing, maybe it helps 😄 Good night.

**Comment by whikloj** [comment]
I'm closing this PR in favour of #20.

**Pull request closed without merging**
